version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379

  mysql:
    image: mariadb:11.3
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: starter-nestjs
