#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/node_modules/@antfu/ni/bin/nci.mjs" "$@"
else 
  exec node  "$basedir/node_modules/@antfu/ni/bin/nci.mjs" "$@"
fi
