# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  STARTER_NESTJS_CONFIG_FILE: ./config-example.yaml

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [16.x]
        os: [ubuntu-latest]
      fail-fast: false

    services:
      redis:
        image: redis:7.0
        ports:
          - 6379:6379
      mariadb:
        image: mariadb:11.3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: starter-nestjs
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install
        run: |
          pnpm install
          cp .env.ci .env

      - name: Lint
        run: pnpm lint

      - name: Prisma Validate
        run: npx prisma validate

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Test Cov
        run: pnpm test:cov

      - name: Upload coverage to CodeCov
        if: contains(matrix.os, 'ubuntu')
        uses: codecov/codecov-action@v2
        with:
          files: coverage/clover.xml
          verbose: true

      - name: e2e Test
        run: pnpm test:e2e
